name: Deploy

on:
  push:
    branches:
      - master # Triggers the workflow on pushes to the master branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify the Node.js version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build the project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Ensure this runs only on the master branch

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
